name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup scripts
      run:  |
            cd scripts
            make
    - name: Generate points
      run: make genpoints
    - name: Compile TSP
      run: make
    - name: Run
      run: make run
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tsp-folder
        path: |
          *.txt
          *.pdf
